Algoritmo "AreaTriangulo"
// Descrição   : Solicita base e altura e calcula a área do triangulo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/03/2022
Var
base,alt,area:real


Inicio
// entrada

escreval("Digite a base: ")
leia(base)

escreval("Digite a altura: ")
leia(alt)

//processamento

area <- (base*alt)/2

escreval("A área do triangulo é igual a: ",area)


Fimalgoritmo