Algoritmo "AreaRetangulo"
// Descrição   : Solicita base e altura e calcula a area do retangulo
// Autor(a)    : Miguel Carneiro de Mendonca
// Data atual  : 08/03/2022
Var
base,alt,area:real


Inicio
//entrada
escreval("Digite a base do retangulo: ")
leia(base)

escreval("Digite a altura do retangulo: ")
leia(alt)

//processamento

area <- base*alt
limpatela

//saida
escreval("A área é igual a: ",area)

Fimalgoritmo
