Algoritmo "MediaAritmetica"
// Descrição   : Calcula a média aritmética de 3 notas
// Autor(a)    : Miguel Carneiro de Mendonça
// Data atual  : 08/03/2022
Var
n1,n2,n3,media:real


Inicio
// entrada
escreval("Digite a primeira nota:")
leia(n1)
escreval("Digite a segunda nota:")
leia(n2)
escreval("Digite a terceira nota:")
leia(n3)

//processamento

media <- (n1+n2+n3)/3

//saida

escreval("A média final é igual a: ",media)


Fimalgoritmo
